import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flexDirection:'column',
        backgroundColor:'#B0E0E0',
        borderRadius:4,
        padding:16,
        margin:10,
    },
    containerText:{
        flexDirection:'row',
        backgroundColor:'#B0E0E0',
        borderRadius:4,
        padding:16,
        margin:10,
    },
    containerButton:{
        flexDirection:'row',
        justifyContent:'center',
        alignContent:'center',
    },
    buttonNew:{
        justifyContent:'center',
        alignContent:'center',
        borderRadius:4,
        paddingVertical:12,
        paddingHorizontal:16,
        marginHorizontal:8,
        backgroundColor:'blue',
        marginBottom:12,
        marginTop:12,

    },
    name:{
        textAlign:'left',
        marginRight:'auto',
        fontSize:16,
        fontWeight:'bold'
    },
    birthday:{
        textAlign:'right',
        marginRight:'auto',
        fontSize:16,
        fontWeight:'bold'
    },
    button:{
        backgroundColor:'blue',
        paddingVertical:12,
        paddingHorizontal:16,
        marginHorizontal:8,
        borderRadius:8,
    },
    buttonText:{
        color:'white',
        fontSize:16,
        fontWeight:'bold',
    },
});